name: Generate config

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run generate
    - name: Upload DEX Kovan config
      uses: actions/upload-artifact@v2
      with:
        name: dex-kovan-data
        path: generated/dex/registry.kovan.json
    - name: Upload DEX Homestead config
      uses: actions/upload-artifact@v2
      with:
        name: pm-homestead-data
        path: generated/pm/registry.homestead.json
    - name: Upload PM Kovan config
      uses: actions/upload-artifact@v2
      with:
        name: pm-kovan-data
        path: generated/pm/registry.kovan.json
    - name: Upload PM Homestead config
      uses: actions/upload-artifact@v2
      with:
        name: dex-homestead-data
        path: generated/dex/registry.homestead.json
    - name: Upload TokenList
      uses: actions/upload-artifact@v2
      with:
        name: tokenlist-data
        path: generated/listed.tokenlist.json
  commit:
    needs: generate
    runs-on: ubuntu-latest
    steps:
    - name: Download PM Kovan config
      uses: actions/download-artifact@v2
      with:
        name: pm-kovan-data
        path: pm
    - name: Download PM Homestead config
      uses: actions/download-artifact@v2
      with:
        name: pm-homestead-data
        path: pm
    - name: Download DEX Kovan config
      uses: actions/download-artifact@v2
      with:
        name: dex-kovan-data
        path: dex
    - name: Download DEX Homestead config
      uses: actions/download-artifact@v2
      with:
        name: dex-homestead-data
        path: dex
    - name: Download TokenList
      uses: actions/download-artifact@v2
      with:
        name: tokenlist-data
        path: .
    - name: Create 'generated' branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: generated
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: balancer-labs/assets
        ref: generated
        path: branch
        fetch-depth: 0
    - name: Commit
      id: commit
      run: |
        cd branch
        cp ../dex/registry.kovan.json generated/dex/registry.kovan.json
        cp ../dex/registry.homestead.json generated/dex/registry.homestead.json
        cp ../pm/registry.kovan.json generated/pm/registry.kovan.json
        cp ../pm/registry.homestead.json generated/pm/registry.homestead.json
        cp ../listed.tokenlist.json generated/listed.tokenlist.json
        git config --global user.email "bot@balancer.finance"
        git config --global user.name "Balancer Bot"
        DIFF_LINES=$(git diff | wc -l)
        if [ $DIFF_LINES -gt 0  ]
        then
          echo "::set-output name=status::commited"
          git add .
          git commit -m "Generate config"
          git push
        fi
    - name: Make PR to master
      if: ${{ steps.commit.outputs.status }}
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: generated
        title: "Update generated files"
        body: "Please trigger Netlify build after merging this."
